update links & images
Epidocs/epita.it pull request #105
Opened 2024-01-23 12:58 UTC by 1somniak

- I put the wiki prog and algo course website in archive because they are not used anymore.
- RocketChat is in archive too because school no longer have access. I dont know if I should just remove it or put it in archive.
- I update some old links like moodle and rosetta stone and image links like zeus and rosetta stone.

2024-01-23 15:43 UTC, matiboux requested changes
Thank you for the changes. The website really needed someone to look over and update what's changed in the past year. 🙏

I've suggested fixes to some of your changes, please review them.

Please also remove commented elements if they are redundant with some from other pages (like with the copies you made, as you meant to move the originals).

As for "Rocket.Chat", it is fine to send it in the archive. That's where I sent other deprecated and replaced resources, so it's welcome there.

However, I wonder about the Algo/Prog wikis: is their content really irrelevant now?
These resources were not used either in my time in Prepa (the Algo wiki even less so than Prog), but their content was nevertheless useful to some students.
Is their content fully redundant with some other resources? If not, please leave them out of the archive. Then, if you wish, we can think about moving them instead in the "Documentation & Resources" page.

2024-01-23 15:43 UTC, matiboux commented on _data/links.yml
> +    background_image: https://upload.wikimedia.org/wikipedia/en/thumb/6/67/Rosetta_Stone_logo.svg/1920px-Rosetta_Stone_logo.svg.png
No need for an oversized logo here.
```suggestion
    background_image: https://upload.wikimedia.org/wikipedia/en/thumb/6/67/Rosetta_Stone_logo.svg/320px-Rosetta_Stone_logo.svg.png
```
This reduces file size from 151 KB to 20 KB.

2024-01-23 15:43 UTC, matiboux commented on _data/archive.yml
> +    - 'background-size: 90%'
Broken indentation here
```suggestion
  - name: Algo Cours (FR)
    href: https://algo.infoprepa.epita.fr/
    class: tile-small-wide text-dark
    background_image: https://algo.infoprepa.epita.fr/skins/common/images/Algo_prepas_epita_wiki_logo.png
    style:
    - 'background-color: #fff'
    - 'background-size: 90%'
```

2024-01-24 09:32 UTC, 1somniak commented
ok I have removed all comments and did the changes requested.
for the algo/prog wikis, they are not used, no one of my teachers mentionned them during my prepa and these websites have not been updated since years.
I think it is better if they go in archive file

2024-01-30 10:37 UTC, matiboux commented
Hello. Firstly, thank you for the changes.

Secondly, please revert changes to algo/prog wikis links. I insist these resources can be of use to students.
After looking at the content, and asking to schoolmates, I still believe their content is relevant.

> no one of my teachers mentionned them during my prepa

That's to be expected: curriculum changed and these wikis are no longer course material.
However, their content is still relevant and the core content have not changed.
For some, it gives another perspective on studied topics. For others, it gives a way to dive deeper in these topics.

> these websites have not been updated since years

The courses at EPITA have evolved but the studied topics are mostly the same. Most of the content of these websites are timeless and still available: courses content, some slides, practical sessions subjects, etc.

In my opinion, even if less than 10% of students use these resources, it is better to keep these resources handy and available while they are still up online, than not.

2024-01-30 11:57 UTC, 1somniak commented
Hello,
I understand, I have done the changes requested :)

2024-01-30 12:38 UTC, matiboux requested changes
Thank you. "Wiki Prog" is still missing.
Once fixed, this'll be all good.

2024-01-30 12:44 UTC, matiboux approved these changes
Thank you for the contribution!

2024-01-30 12:45 UTC, 1somniak commented
Sorry, I thought I added it ^^'
It's the last one I hope

2024-01-30 12:45 UTC, matiboux commented
> Sorry, I thought I added it ^^' It's the last one I hope

All good! Sorry for the ping-pong game.

2024-01-30 12:46 UTC, merged