Update link intracom
Epidocs/epita.it pull request #83
Opened 2022-09-13 09:39 UTC by OwOthmane

Stan Cassie

2022-09-13 09:41 UTC, CL0Pinette commented
CHAD !

2022-09-13 21:28 UTC, matiboux requested changes
Seems like the Platform was moved to https://intracom.epita.fr/.
`intracom-new.epita.fr` shows `404 page not found`.

So the pull request seems outdated to me.

However, the pull request would be still useful for upgrading the link to `https` (though not required). I'll propose changes for that.

Tell me if I'm wrong! Otherwise I'll merge changes in, let's say, 20 hours or so.

2022-09-13 21:28 UTC, matiboux commented on _data/links.yml
> +    href: https://intracom-new.epita.fr/
```suggestion
    href: https://intracom.epita.fr/
```

2022-09-15 08:11 UTC, matiboux approved these changes
There! Upgraded the link to https but also updated the background image.
Thanks for the PR.

2022-09-15 08:12 UTC, merged