Epita logo in the javascript console
Epidocs/epita.it pull request #97
Opened 2023-06-10 09:42 UTC by thisiskeanyvy

I am reopening the PR following this one : #95

- Displaying the Epita logo encoded in ASCII in the JavaScript console. (script.js)

![console](https://github.com/Epidocs/epita.it/assets/48371699/7f68afc0-891c-4484-8073-1474fe1b4299)

2023-06-10 20:30 UTC, matiboux commented
Copying my comment from the previous PR:

> Why is the ascii background (with @ characters) chunky?
> 
> Wouldn't it be better to have a rectangular filled background with @ characters?
> Or better yet: no background at all, and just use ascii characters for the logo itself.
> What do you think?

To what ChatGPT replied, through you:

> [...] using a rectangular filled background with "@" characters may result in a more visually appealing and consistent display.
> [...] opting for no background and solely using ASCII characters for the logo itself can provide a cleaner and more focused representation.
> 
> [...] the decision on the design and appearance of the [...] logo should consider factors such as readability, aesthetics, and adherence to the overall visual style of Epita.

2023-06-10 23:27 UTC, thisiskeanyvy commented
- As I said, I pushed a commit without the background and squashed the commits into one

![ascii](https://github.com/Epidocs/epita.it/assets/48371699/44e16c7f-6935-4b53-a8b5-f0a4c0de6b34)

2023-06-11 10:38 UTC, matiboux commented
As you did not said, you did.

Will review in the following days and merge.

2023-06-11 20:12 UTC, matiboux requested changes
Left comments and code suggestions. The code is low quality.

2023-06-11 20:12 UTC, matiboux commented on assets/js/script.js
> +        setTimeout(console.log("                                                                                \n                                   ????                 ((((                    \n
What's the point of `setTimeout`?
The console log function is executed in-place. 
So your code has a type error: `setTimeout` takes `void` as argument.

Also for readability: multi-line string.

```suggestion
       console.log(`
                                   ????                 ((((
                                ????????  (((        ((((((((
                            ???????????? (((((((  ((((((((((((
                        ????????#??####?(((((((((((((((((((((((
                    ####################((((((((((((((((((((((((
                ##########################################(((((((
            ##        (###       ####??   ##            #####  (((
        ######   #########   ###   ????   #######   ########/   ###
    ##########   #########   #???   ???   #######   ########     ###
 (((((((((((((        ((((   ????   ???   #######   #######   #   ###((#
    ((((((((((   ((((((???   ?(    ????   ???????   ??????   ???   ???#####
        ((((((   (((??????      ???????   ???????   ?????           ???#######
           (((        #???   ??????????   ???????   ????   ???????   ???#####
             ??????????????&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&??????
          ???? ??????  ?? && & &  &  &&? & & ?& && &  && & ???? ??   ?????
       ???????????????&&&&&&&&&&&&&&&&&&&&&&&&&&???????????????????????????
                       ???????????????(((
                      ?????? ((((((((((((
                                 ((((((((
                                    ((((((
                                        ((
`)
```

2023-06-11 20:12 UTC, matiboux commented on assets/js/script.js
> +    console.clear()
As suggested by the condition on line 99, `console` may be undefined here.
This line of code is stupid.

```suggestion
```

2023-06-11 20:15 UTC, matiboux commented on assets/js/script.js
> +    console.clear()
Oh and inconsistent indentation as a bonus.

2023-06-11 20:15 UTC, closed without merging

2023-06-11 20:50 UTC, thisiskeanyvy commented
.

2023-06-11 20:50 UTC, thisiskeanyvy commented
.

2023-06-11 20:50 UTC, thisiskeanyvy commented
a

2023-06-11 20:51 UTC, thisiskeanyvy commented
b

2023-06-11 20:56 UTC, thisiskeanyvy commented
coinbasewallet: {
      package: CoinbaseWalletSDK,
      options: {
        appName: "BuyWithCrypto",
        infuraId: "b54ec21d469a4b0586bce17b6605e643",
        rpc: "",
        chainId: 1,
        darkMode: false
      }
    }